#!/bin/sh

user_shell () {
  busybox mount -t tmpfs dev /dev
  mkdir -p /dev/pts
  busybox mount -t devpts devpts /dev/pts

  echo '  Entering rescue shell.'
  setsid cttyhack sh
  /bin/busybox sh

}

sys_init () {

  busybox mount -t proc proc /proc
  busybox mount -t sysfs sysfs /sys
  echo "mdev" > /proc/sys/kernel/hotplug
  echo 0 > /proc/sys/kernel/printk
  mknod /dev/null c 1 3
  chmod 777 /dev/null
  mdev -s
}

sys_deinit () {

  echo "" > /proc/sys/kernel/hotplug
  rm /dev/null
  umount -l /proc
  umount -l /sys

}


main () {
  export PATH=/bin:/sbin:/usr/bin:/usr/sbin

  INIT_ARGS="$(awk '{gsub(/[[:graph:]]+=[[:graph:]]+/,""); print}' /proc/cmdline)"
  # remove any initramfs commands from INIT_ARGS
  INIT_ARGS="$(echo $INIT_ARGS | awk '{gsub(/shell/,""); print}')"
  INIT_ARGS="$(echo $INIT_ARGS | awk '{gsub(/init_debug/,""); print}')"
  INIT_ARGS="$(echo $INIT_ARGS | awk '{gsub(/ssh_key/,""); print}')"
  INIT_ARGS="$(echo $INIT_ARGS | awk '{gsub(/command_url/,""); print}')"
  REAL_ROOT='/tmp/realroot'

  export $INIT_ARGS

  # Parse out kernel arguments
  for arg in $(cat /proc/cmdline); do
    case $arg in
      init_debug)
        DEBUG=yes
        ;;
      shell)
        EXEC_SHELL=yes
        ;;
      ssh_keys_url=*)
        SSH_KEY_URL="${arg#*=}"
        ;;
      command_url=*)
        CMD_URL="${arg#*=}"
        ;;

    esac
  done

  mkdir $REAL_ROOT
  mount -o loop /system.img $REAL_ROOT

  # Process anything specified by a kernel arg we handle
  [ "$DEBUG" == "yes" ] && set -x
  [ -n "$SSH_KEY_URL"  ] && echo "$SSH_KEY_URL" > $REAL_ROOT/etc/key_url
  if [ -n "$CMD_URL"  ];then
    echo "curl $CMD_URL > /tmp/bootstrap; bash /tmp/bootstrap" > $REAL_ROOT/etc/local.d/01-bootstrap.start
    chmod +x $REAL_ROOT/etc/local.d/01-bootstrap.start
  fi

  if [ "$EXEC_SHELL" == "yes" ];then
    user_shell
  fi

  sys_deinit
  if ! exec switch_root $REAL_ROOT /sbin/init ;then
    echo "Pivoting to new sytem failed :( you're on your own, good luck!"
    user_shell
  fi
}

sys_init
trap 'user_shell' SIGHUP SIGINT SIGTERM
main
