#!/bin/bash -ex

function autoemerge
{
  set +e
  time emerge -nNv $@
  rc=$?

  if [ "$rc" -ne  "0" ];then
    echo "Trying to autounmask"
    emerge -nNv $@ --autounmask-write
    echo "-5" | etc-update
    time emerge $@ || { echo "Failed emerge"; exit 1; }
  fi

  set -e
}

function emerge_world
{
  set -e  
  export DONT_MOUNT_BOOT=1
  autoemerge --update --deep --tree -k --noreplace  world 
}
